### ISSUE TITLE
Loading shielded context takes too long time on SE

### ISSUE THREAD

**Issue by TuanTQ15** [anoma/namada-interface#663] opened 2024-03-13 07:31 UTC

**Comment by pnam1609** [comment] 2024-03-13 07:37
Too long for load block to shielded context and scaning. In SE have more than 120k block. It take maybe 3 - 4 days for fetching block and whenever rpc is or some thing is failed, it make function break. And we need load shielded context again.

**Comment by pnam1609** [comment] 2024-03-13 07:39
Take a long time to shieled sync. Who one need use shieled action.

**Comment by mateuszjasiuk** [comment] 2024-03-21 13:27
Duplicate of #662

**Closed by mateuszjasiuk** 2024-03-21 13:27 UTC
