### ISSUE TITLE
Spend long time for fetching MASP in browser and often break process when 1 block fetching failed

### ISSUE THREAD

**Issue by pnam1609** [anoma/namada-interface#668] opened 2024-03-16 14:11 UTC
### Issue
- When fetching block to serialize to shielded context, API will be called 1 by 1. It take a long time.
- Often crashes fetching MASP process because there are many block in SE network and 1 block fetches the API crashes. It make process is down. So we need start process again
- Proof issue image:
![image](https://github.com/anoma/namada-interface/assets/44290296/784345a0-00d5-4173-9576-5836f2355d35)

**Comment by mateuszjasiuk** [comment] 2024-03-21 13:28
Duplicate of #662

**Closed by mateuszjasiuk** 2024-03-21 13:28 UTC
