### ISSUE TITLE
Unable to fetch or Display shielded balance

### ISSUE THREAD

**Issue by chimmykk** [anoma/namada-interface#639] opened 2024-02-20 07:51 UTC
Provide a proper docs or writeup on how to implement display >shielded balance on the interface

**Comment by chimmykk** [comment] 2024-02-21 06:43
Shielded balance does not show up on namada interface when setup on a local chain.

Transparent balance does show up except for the shielded balance.

**Comment by chimmykk** [comment] 2024-02-21 06:43
> Shielded balance does not show up on namada interface when setup on a local chain.
> 
> Transparent balance does show up except for the shielded balance. 

So I'm specifically referring to the namada - interface

Any changes or update I need to make so that the shielded balance show up

**Comment by emccorson** [comment] 2024-02-21 07:08
I'm pretty sure this is not a bug, since shielded balances are working locally for me.

One thing about shielded balances is that they currently take longer to load than the transparent balances. Also, the longer your local chain has been running, the longer the shielded balances take to load. We will hopefully be fixing that in the future though.

When balances are loading, the interface displays "-" for the balance. If shielded balances display as "-", that means you just need to wait until they load.

If the balance displays as "0" even though you have a non-zero balance, that probably means the query to get the shielded balance has timed out. This will also display as an error in the extension (not interface) console. In that case, you can try resetting your chain (due to the problem mentioned already with balances taking longer to load the longer your chain has been running). If you are running everything locally, you can also increase the query timeout ([here](https://github.com/anoma/namada-interface/blob/268ae4bc605c081311a7789cf351fe32d3f13adf/packages/shared/src/index.ts#L48)).

This is the best workaround I can give for now until we fix the problem with shielded balance loading generally. I will close this for now as it doesn't seem to be a bug.

**Closed by emccorson** 2024-02-21 07:08 UTC

**Comment by chimmykk** [comment] 2024-02-21 17:07
Well updating the timeout does not work either can you refer me to your working directory or codebase, tried a lot seem like there's an issue.

**Comment by emccorson** [comment] 2024-02-26 07:31
The codebase is just the main branch of this repository. You might also check your Namada version - it should be v0.31.4 currently. Also check the README of this repo and make sure you have followed the setup instructions correctly there (and if there is something that looks out of date in the README, please let us know!). Once you have tried that, if it is still not working please link your repository with a minimum reproducible example of the problem and I will take a look at it.
