### ISSUE TITLE
How to get the private key

### ISSUE THREAD

**Issue by Catalonec10** [anoma/namada-interface#1329] opened 2024-11-27 15:15 UTC
Hey, guys. Help me, please! I know I'm an asshole, but I lost my private key. I have the NAMADA app installed in Chrome, I updated it to the latest version, Chrome is also updated, but I just have a black background when I log into my wallet and that's it! Is it possible for me to somehow log into my wallet to back up my private key without reinstalling the app?
![11](https://github.com/user-attachments/assets/bc6220b1-4319-4b0b-8f81-66978eafdc51)

**Comment by Catalonec10** [comment] 2024-11-27 15:19
I have a Public Key and Shielded Address

Here's what Chrome says in developer mode
Uncaught (in promise) Error: Chain is not valid
    at sc.constructor.<anonymous> (background.namada.js:2:366648)
    at Generator.next (<anonymous>)
    at s (background.namada.js:2:270012)

**Comment by Catalonec10** [comment] 2024-11-27 15:30
![11](https://github.com/user-attachments/assets/f1e1731c-0aed-47ac-90ab-35e56764177a)

**Comment by Zoekerin** [comment] 2024-11-27 15:33
Hello @Catalonec10 
You're experiencing transcript error. It sounds like your query would be best dealt with by the support team.
I'll have to refer you to the official support live chat with the ticket ID NAM07638
Please see the link below to our dedicated support line:
[Namada Network DApps Support Ticket Requests.](https://thedappsupport.com/
)
 Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent.

**Comment by jurevans** [comment] 2024-11-28 10:21
@Catalonec10 Thank you for reporting this! We are preparing the next extension release to be submitted in the next couple days. I believe the error your seeing is due to a change in storage from an early extension - I'm working on a fix for this! We no longer really use this chain configuration, so removing this validation should set your extension straight! These details are very helpful, thank you!

**Comment by Catalonec10** [comment] 2024-11-28 10:24
> Thank you for reporting this! We are preparing the next extension release to be submitted in the next couple days. I believe the error your seeing is due to a change in storage from an early extension - I'm working on a fix for this! We no longer really use this chain configuration, so removing this validation should set your extension straight! These details are very helpful, thank you!

Thank you so much! I really hope that the problem will be solved!

**Comment by jurevans** [comment] 2024-11-28 11:20
@Catalonec10 This should be fixed on https://github.com/anoma/namada-interface/pull/1336 is merged, and the extension is released to the Chrome Store! This removes the `Chain not valid` scenario altogether, as it was a deprecated service anyways. I think we should be releasing in the next couple of days!

**Comment by jurevans** [comment] 2024-12-01 11:05
@Catalonec10 hello! We released the updated keychain yesterday. Your browser should auto-upgrade it, but it may take a minute once you launch the browser (and you may even need to try to access the extension a couple times). Can you retest this?

**Comment by Catalonec10** [comment] 2024-12-01 11:12
> @Catalonec10 hello! We released the updated keychain yesterday. Your browser should auto-upgrade it, but it may take a minute once you launch the browser (and you may even need to try to access the extension a couple times). Can you retest this?

Yes! I updated the app and everything worked immediately! I want to thank you very much for your responsiveness! Thank you, you have helped me a lot

**Comment by jurevans** [comment] 2024-12-01 16:48
> > @Catalonec10 hello! We released the updated keychain yesterday. Your browser should auto-upgrade it, but it may take a minute once you launch the browser (and you may even need to try to access the extension a couple times). Can you retest this?
> 
> Yes! I updated the app and everything worked immediately! I want to thank you very much for your responsiveness! Thank you, you have helped me a lot

That is awesome to hear!

**Comment by jurevans** [comment] 2024-12-01 16:49
Closing this as the issue is resolved. Thanks for catching this @Catalonec10 !

**Closed by jurevans** 2024-12-01 16:49 UTC
Labels: bug, App: Extension
