### ISSUE TITLE
Fetching shielded balance via SDK nor extension working

### ISSUE THREAD

**Issue by zenodeapp** [anoma/namada-interface#662] opened 2024-03-12 15:40 UTC
Hey,

![image](https://github.com/anoma/namada-interface/assets/108588903/08ad53a9-e713-4d22-a880-81f65d47c2ae)

Whenever I attempt to query a shielded balance for a viewing key via the SDK, I get just a lot of POST request to my rpc endpoint. This just continue to go on. While I don't mind to wait whether it will actually result in something, this will definitely not be feasible for a multiple user front-end.

The extension way gives a:
`Error: No results have been found on Vault`-error.

Again, this is probably due to the current shielded-sync approach and you guys are likely working at it. But wanted to express this as to see whether it's a me-problem or a common one amongst us all.

ZEN

**Comment by zenodeapp** [comment] 2024-03-12 15:42
Close this asap if it's already a known issue. Don't wanna let the issues tab become bloated like the main `namada`-repository 😅.

**Comment by thousandsofthem** [comment] 2024-03-13 12:48
Extension without balances is pretty useless, if i can't see own balance then i can't use shielded transactions. Don't work for me as well

**Comment by pnam1609** [comment] 2024-03-21 14:24
This is my PR to reduce time fetching MASP. Now i still working on it https://github.com/anoma/namada-interface/pull/667

**Comment by mateuszjasiuk** [comment] 2024-03-22 10:18
Hello. To give you more context about the issue. The problem is that atm we have to query each block to produce shielded context which takes a long time. For SE, as of now, it means querying 160 000 blocks. If you use interface(namada.me) this won't work as we timeout query function after some time(there was a reason for that which is not really that important to this conversation :)).

What is more:
- if you did not do any shileding/unshielding this means querying 160 000 each time as context is only saved when it detects some change in relation to viewing keys that you provided. This also means that once you add another shielded account you have to query everything from the beginning
- if you made shielding transfer at block 100 000, and once you fetched shielded context, this means that every next shielded context fetch will start from block 100 000
- currently published extension uses Namada SDK in version 0.31.8 which is outdated and some of the functionalities might not work with the SE

Upsides:
- we have a [0.32.0 bump PR](https://github.com/anoma/namada-interface/pull/673) which removes the timeout for `query_balance`
- there was a recent change to the Namada SDK which allows you to pass a block index that is a starting index of the shielded context fetch, which allows to write some improvements, like storing index of last fetched block in frontend or whatnot

**Comment by zenodeapp** [comment] 2024-03-27 16:04
> Hello. To give you more context about the issue. The problem is that atm we have to query each block to produce shielded context which takes a long time. For SE, as of now, it means querying 160 000 blocks. If you use interface(namada.me) this won't work as we timeout query function after some time(there was a reason for that which is not really that important to this conversation :)).
> 
> What is more:
> 
> * if you did not do any shileding/unshielding this means querying 160 000 blocks each time as context is only saved when it detects some change in relation to viewing keys that you provided. This also means that once you add another shielded account you have to query everything from the beginning
> * if you made shielding transfer at block 100 000, and once you fetched shielded context, this means that every next shielded context fetch will start from block 100 000
> * currently published extension uses Namada SDK in version 0.31.8 which is outdated and some of the functionalities might not work with the SE
> 
> Upsides:
> 
> * we have a [0.32.0 bump PR](https://github.com/anoma/namada-interface/pull/673) which removes the timeout for `query_balance`
> * there was a recent change to the Namada SDK which allows you to pass a block index that is a starting index of the shielded context fetch, which allows to write some improvements, like storing index of last fetched block in frontend or whatnot

Hey thanks for this update and thorough description! I'll check this out at the end of this week and see what I can do to get something working with the current state of the SDK!

**Comment by jurevans** [comment] 2024-09-26 12:16
@zenodeapp Hello! Just FYI - I'm closing this issue as we're revamping shielded balances right now. Thanks!

**Closed by jurevans** 2024-09-26 12:16 UTC
Labels: bug, App: Namadillo, discussion
